- hosts: all
  gather_facts: false
  tasks:
    - name: get login token
      uri:
        url: http://gitlab/api/v4/session
        body: "login=root&password=password"
        return_content: yes
        follow_redirects: yes
        method: POST
        status_code: 200,201
      register: logindata
      delegate_to: localhost

    - name: include feature
      include: demo/feature.yaml

    - name: include release
      include: demo/release.yaml

    - name: include hotfix
      include: demo/hotfix.yaml