FROM gitlab/gitlab-runner

ENV REGISTER_RUN_UNTAGGED=true \
    CI_SERVER_URL=http://gitlab \
    REGISTRATION_TOKEN=rv5s57hsXxPNBXQghPV3 \
    REGISTER_NON_INTERACTIVE=true \
    REGISTER_RUN_UNTAGGED=true \
    RUNNER_TAG_LIST=docker \
    RUNNER_EXECUTOR=docker \
    DOCKER_IMAGE=centos:7 \
    DOCKER_NETWORK_MODE=dockergitlabci_gitlabci